version: '3'

services:
    web-nginx:
        image: nginx:stable-alpine
        container_name: web-nginx
        volumes:
            - "./docker-web-mv/www:/usr/share/nginx/html:ro"
            - "./docker-web-mv/log:/var/log/nginx"
            - "./docker-web-mv/nginx.conf:/etc/nginx/nginx.conf:ro"
        ports:
            - "80:80"

    web-php:
        image: php:fpm-alpine
        container_name: web-php
        volumes:
            - "./docker-web-mv/www:/script:ro"
